### PR TITLE
Parking session modal

### PR DESCRIPTION
**Pull request by keenangee**
Added modal to let user continue last session if logging back in, updated google sign in so that it didn't create a new user everytime

### CODE REVIEW

**Comment by ah28011992** [comment]
Nice, seems to work fine on mine. On submit of the form, it no longer redirects to the homescreen unless that is something with intention now ?

**Comment by keenangee** [comment]
> 

Mine still redirects back, I know if you don't take a picture it doesn't submit the form. Will take a look though

**Comment by ah28011992** [comment]
@keenangee yeah you're right, i'll add a ticket to trello board to handle that.

**Review by ah28011992 — APPROVED** [review]
Modal works ok on android

**Pull request merged**
